### ISSUE TITLE
3.simulation on stage with genarated sc (run stage) 

### ISSUE THREAD

**Issue by x-has** [Idontwan/SISG4HEI_Alpha#3]
ONE@DESKTOP-3EBHGPF MINGW64 /e/SISG4HEI_Alpha-windows/Outputs/0/Stage
$ roscore
bash: roscore: command not found
 LIKE VIDEO BUT I THINK THIS INSTRUCTION NOT VALAIABLE ON WINDOWS (roscore)

**Comment by Idontwan** [comment]
when I write the code, windows version of ROS is very rare. I had never run stage, gazebo on windows. 
But i think if you can figure out how to run gazebo or stage on windows, you can use the generated files
